# container for build

FROM ghcr.io/userver-framework/docker-userver-build-base:nightly as build

RUN apt-get install -y --allow-unauthenticated libcrypto++-dev libcrypto++-doc libcrypto++-utils

WORKDIR /HSERank/backend/build